swagger: "2.0"
info:
  title: User
  version: "1.0"
host: "localhost:3000"
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /users:
    get:
      summary: ユーザー一覧を取得します
      tags:
        - User
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
      operationId: get-users
  "/users/{userId}":
    parameters:
      - type: string
        name: userId
        in: path
        required: true
    get:
      summary: 特定のユーザーを取得します
      tags:
        - User
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/User"
      operationId: get-users-userId
definitions:
  User:
    description: ""
    type: object
    x-examples:
      example-1:
        id: 1
        name: Leanne Graham
        username: Bret
        email: Sincere@april.biz
        address:
          street: Kulas Light
          suite: Apt. 556
          city: Gwenborough
          zipcode: 92998-3874
          geo:
            lat: "-37.3159"
            lng: "81.1496"
        phone: 1-770-736-8031 x56442
        website: hildegard.org
        company:
          name: Romaguera-Crona
          catchPhrase: Multi-layered client-server neural-net
          bs: harness real-time e-markets
    properties:
      id:
        type: number
      name:
        type: string
        minLength: 1
      username:
        type: string
        minLength: 1
      email:
        type: string
        minLength: 1
      address:
        type: object
        required:
          - street
          - suite
          - city
          - zipcode
          - geo
        properties:
          street:
            type: string
            minLength: 1
          suite:
            type: string
            minLength: 1
          city:
            type: string
            minLength: 1
          zipcode:
            type: string
            minLength: 1
          geo:
            type: object
            required:
              - lat
              - lng
            properties:
              lat:
                type: string
                minLength: 1
              lng:
                type: string
                minLength: 1
      phone:
        type: string
        minLength: 1
      website:
        type: string
        minLength: 1
      company:
        type: object
        required:
          - name
          - catchPhrase
          - bs
        properties:
          name:
            type: string
            minLength: 1
          catchPhrase:
            type: string
            minLength: 1
          bs:
            type: string
            minLength: 1
    required:
      - address
      - phone
      - website
      - company
